// Code generated by protoc-gen-go.
// source: responseUpcase.proto
// DO NOT EDIT!

/*
Package responseUpcase is a generated protocol buffer package.

It is generated from these files:
	responseUpcase.proto

It has these top-level messages:
	Request
	Response
*/
package responseUpcase

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Word string `protobuf:"bytes,1,opt,name=word" json:"word,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Response struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*Request)(nil), "responseUpcase.Request")
	proto.RegisterType((*Response)(nil), "responseUpcase.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for ConvertToUpcase service

type ConvertToUpcaseClient interface {
	ConvertToUpcase(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type convertToUpcaseClient struct {
	cc *grpc.ClientConn
}

func NewConvertToUpcaseClient(cc *grpc.ClientConn) ConvertToUpcaseClient {
	return &convertToUpcaseClient{cc}
}

func (c *convertToUpcaseClient) ConvertToUpcase(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/responseUpcase.ConvertToUpcase/convertToUpcase", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ConvertToUpcase service

type ConvertToUpcaseServer interface {
	ConvertToUpcase(context.Context, *Request) (*Response, error)
}

func RegisterConvertToUpcaseServer(s *grpc.Server, srv ConvertToUpcaseServer) {
	s.RegisterService(&_ConvertToUpcase_serviceDesc, srv)
}

func _ConvertToUpcase_ConvertToUpcase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConvertToUpcaseServer).ConvertToUpcase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/responseUpcase.ConvertToUpcase/ConvertToUpcase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConvertToUpcaseServer).ConvertToUpcase(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConvertToUpcase_serviceDesc = grpc.ServiceDesc{
	ServiceName: "responseUpcase.ConvertToUpcase",
	HandlerType: (*ConvertToUpcaseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "convertToUpcase",
			Handler:    _ConvertToUpcase_ConvertToUpcase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("responseUpcase.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x4a, 0x2d, 0x2e,
	0xc8, 0xcf, 0x2b, 0x4e, 0x0d, 0x2d, 0x48, 0x4e, 0x2c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x43, 0x15, 0x55, 0x92, 0xe5, 0x62, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11,
	0x12, 0xe2, 0x62, 0x29, 0xcf, 0x2f, 0x4a, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3,
	0x95, 0x94, 0xb8, 0x38, 0x82, 0xa0, 0x1a, 0x84, 0xc4, 0xb8, 0xd8, 0x80, 0x9a, 0x4b, 0x73, 0x4a,
	0xa0, 0x2a, 0xa0, 0x3c, 0xa3, 0x48, 0x2e, 0x7e, 0xe7, 0xfc, 0xbc, 0xb2, 0xd4, 0xa2, 0x92, 0x90,
	0x7c, 0x88, 0xa9, 0x42, 0x6e, 0x5c, 0xfc, 0xc9, 0x68, 0x42, 0xe2, 0x7a, 0x68, 0xee, 0x81, 0x5a,
	0x2b, 0x25, 0x81, 0x29, 0x01, 0xe1, 0x2a, 0x31, 0x24, 0xb1, 0x81, 0x1d, 0x6d, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0xb2, 0xc5, 0x3d, 0xab, 0xcc, 0x00, 0x00, 0x00,
}
